// ---------------------------
// This file was generated by Nango (v0.58.7)
// You can version this file
// ---------------------------

export interface GithubRepositoryInput {
  owner: string;
  repo: string;
  isOutsideContributor?: boolean;
  isBot?: boolean;
  daysOpenBeforeMerged?: number;
  numberOfDaysOpen?: number;
};

export interface Organization {
  id: string;
  name: string;
  url: string;
  avatarUrl: string;
  description: string;
  websiteUrl: string;
};

export interface Author {
  id: string;
  url: string;
  bio: string;
  avatarUrl: string;
  location: string;
  organizations: Organization[];
};

export interface PullRequest {
  id: string;
  url: string;
  title: string;
  author: Author;
  labels: string[];
  numberOfComments: number;
};

export interface Commit {
  id: string;
  url: string;
  author?: Author;
  branch: string;
  message: string;
  additions: number;
  deletions: number;
  changedFiles: number;
};

export interface StarGazer {
  id: string;
  user: Author;
  createdAt: Date;
};
